# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TudoNosso' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TudoNosso


  target 'TudoNossoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TudoNossoUITests' do
    # Pods for testing
  end
  
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Firebase/Analytics'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
end
