# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TudoNosso' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TudoNosso


  target 'TudoNossoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TudoNossoUITests' do
    # Pods for testing
  end
pod 'MessageKit'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore', '~> 6.12.0'
pod 'Firebase/Analytics'
pod 'SDWebImage', '~> 5.0'
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == 'MessageKit'
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '5.0'
              end
          end
      end
  end
end
